pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'dev',
                    url: 'https://github.com/JayJi5204/StudiOn.git'
            }
        }

        stage('Prepare .env') {
            steps {
                withCredentials([file(credentialsId: 'env-file-id', variable: 'ENV_FILE')]) {
                    sh '''
                        echo "WORKSPACE: $(pwd)"

                        mkdir -p infra
                        cp "$ENV_FILE" infra/.env

                        echo "=== ENV CHECK ==="
                        ls -al infra
                        cat infra/.env
                    '''
                }
            }
        }

        stage('Docker Run') {
            steps {
                sh '''
                    cd infra

                    echo "Docker Compose Down"
                    docker-compose down || true

                    echo "Docker Compose Up"
                    docker-compose up -d
                '''
            }
        }
    }

    post {
        success {
            echo 'Deploy Success'
        }
        failure {
            echo 'Deploy Failed'
        }
    }
}