pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'dev',
                    url: 'https://github.com/JayJi5204/StudiOn.git'
            }
        }

        stage('Prepare .env') {
            steps {
                withCredentials([file(credentialsId: 'env-file-id', variable: 'ENV_FILE')]) {
                    sh '''
                        echo "Copying .env file..."
                        cp $ENV_FILE infra/.env
                        ls infra
                    '''
                }
            }
        }

        stage('Docker Build & Run') {
            steps {
                sh '''
                    cd infra

                    echo "Docker Compose Down"
                    docker compose down

                    echo "Docker Compose Build"
                    docker compose build

                    echo "Docker Compose Up"
                    docker compose up -d
                '''
            }
        }
    }

    post {
        success {
            echo 'Deploy Success'
        }
        failure {
            echo 'Deploy Failed'
        }
    }
}