CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS board_db;
CREATE DATABASE IF NOT EXISTS comment_db;
CREATE DATABASE IF NOT EXISTS room_db;
CREATE DATABASE IF NOT EXISTS chat_db;
CREATE DATABASE IF NOT EXISTS group_chat_db;
CREATE DATABASE IF NOT EXISTS alarm_db;