server:
  port: 0

spring:
  application:
    name: user-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  profiles:
    active: dev

#  config:
#    import: "optional:configserver:http://127.0.0.1:8888"

#  cloud:
#    config:
#      name: test

  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}

  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  output:
    ansi:
      enabled: "always"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Spring Boot


#token:
#  secret: ${TOKEN_SECRET}
#  access-expiration-time: ${ACCESS_TOKEN_EXPIRATION_TIME}
#  refresh-expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, busrefresh
