server:
  port: 8888

spring:
  application:
    name: config-server

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  output:
    ansi:
      enabled: "always"

  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URL}
          search-paths: StudiOn_Config
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, httpexchanges, busrefresh
