server:
  port: 8888

spring:
  application:
    name: config-server

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  output:
    ansi:
      enabled: "always"


  cloud:
    config:
      server:
        git:
          uri: https://github.com/JayJi5204/SpringCloudConfig
          search-paths: StudiOn_Config
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
          default-label: main
#        native:
#          search-locations: file:///Users/jayji/Desktop/StudiOn/config

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, httpexchanges, busrefresh
