server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: gateway-server

  config:
    import: "optional:configserver:"

  output:
    ansi:
      enabled: "always"

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: GlobalFilter
              args:
                baseMessage: Spring Cloud Gateway WebFlux Global Filter
                preLogger: true
                postLogger: true
          routes:
            # 1. USER-SERVICE
            - id: user-service-public
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/health-check, 
                  /user-service/api/users/create, 
                  /user-service/api/users/login, 
                  /user-service/v3/api-docs/**, 
                  /user-service/swagger-ui/**, 
                  /user-service/swagger-ui.html
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*),/$\{segment}

            - id: user-service-secure
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/**
              filters:
                - name: AuthorizationHeaderFilter
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*),/$\{segment}

            # 2. BOARD-SERVICE
            - id: board-service-public
              uri: lb://BOARD-SERVICE
              predicates:
                - Path=/board-service/health-check, 
                  /board-service/v3/api-docs/**, 
                  /board-service/swagger-ui/**, 
                  /board-service/swagger-ui.html
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/board-service/(?<segment>.*),/$\{segment}

            - id: board-service-secure
              uri: lb://BOARD-SERVICE
              predicates:
                - Path=/board-service/**
              filters:
                - name: AuthorizationHeaderFilter
                - RemoveRequestHeader=Cookie
                - RewritePath=/board-service/(?<segment>.*),/$\{segment}

            # 3. COMMENT-SERVICE
            - id: comment-service-public
              uri: lb://COMMENT-SERVICE
              predicates:
                - Path=/comment-service/health-check, 
                  /comment-service/v3/api-docs/**, 
                  /comment-service/swagger-ui/**, 
                  /comment-service/swagger-ui.html
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/comment-service/(?<segment>.*),/$\{segment}

            - id: comment-service-secure
              uri: lb://COMMENT-SERVICE
              predicates:
                - Path=/comment-service/**
              filters:
                - name: AuthorizationHeaderFilter
                - RemoveRequestHeader=Cookie
                - RewritePath=/comment-service/(?<segment>.*),/$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, httpexchanges

springdoc:
  api-docs:
    enabled: true   # 🔥 중요 (Gateway는 문서 생성 안 함)

  swagger-ui:
    persistAuthorization: true
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: board-service
        url: /board-service/v3/api-docs
      - name: comment-service
        url: /comment-service/v3/api-docs